obj-y := q6asm.o q6adm.o q6afe.o
obj-$(CONFIG_SND_SOC_VOICE) += q6voice.o
#ifdef SKY_SND_QSOUND_OPEN_DSP //20120618 jhsong : audio effect in open dsp  //FEATURE_PANTECH_SND_QSOUND_OPEN_DSP
obj-y += pantech_aud_ctl.o
